apiVersion: v1
kind: Service
metadata:
  labels:
    app: apiserver
  name: apiserver
spec:
  type: NodePort
  ports:
  - name: "apiserver"
    port: 80
    targetPort: 3000
  selector:
    app: apiserver

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiserver
  labels:
    app: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - name: apiserver-container
        image: %%IMAGE%%
        imagePullPolicy: Always
        ports:
        - containerPort: 3000


