---
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    app: apiserver
    name: development
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apiserver
  name: apiserver
  namespace: development
spec:
  type: NodePort
  ports:
  - name: "apiserver"
    port: 8082
    targetPort: 3000
  selector:
    app: apiserver
  externalIPs:
  - 192.168.99.100
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apiserver
  namespace: development
  labels:
    app: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - name: apiserver-container
        image: %%IMAGEURL%%
        imagePullPolicy: Always
        ports:
        - containerPort: 3000


