#!/bin/sh

DOCKER_IMAGE=test
DOCKER_REPO=k8s.local:5000
IMAGE_VERSION=latest
KUBECONFIG_PATH=~/.kube/config

#git pull https://github.com/georgej-github.com/sbsw-apiserver-exercise.git

#cd sbsw-apiserver-exercise

set -x

docker build -t $DOCKER_IMAGE -f ./docker/Dockerfile ./
r=$?
set +x
[ $r -ne 0 ] && echo "Build of docker image failed, aborting" && exit 1 
set -x

docker tag $DOCKER_IMAGE $DOCKER_REPO/$DOCKER_IMAGE:$IMAGE_VERSION
docker push $DOCKER_REPO/$DOCKER_IMAGE:$IMAGE_VERSION

mkdir -p manifests/autogenerated
sed "s|%%IMAGEURL%%|${DOCKER_REPO}/${DOCKER_IMAGE}:${IMAGE_VERSION}|g" manifests/apiserver.yml > manifests/autogenerated/apiserver.yml

export KUBECONFIG=${KUBECONFIG_PATH}
kubectl apply -f manifests/autogenerated/apiserver.yml



